Annotation of PXD005507
bigbio/proteomics-metadata-standard pull request #427
Opened 2020-08-28 06:15 UTC by Ohwey

2020-08-31 10:50 UTC, Ohwey commented on annotated-projects/PXD005507/sdrf.tsv
> +sample1	homo sapiens	"NT=Liver;AC=NCIT:C12392"	epithelial cell	"NT=hepatocellular carcinoma;AC=DOID:684"	"NT=HepG2;AC=EFO:0001187"	OEII15635	OEII15635.raw	ftp://ftp.pride.ebi.ac.uk/pride/data/archive
My bugfix commit solves this issue. Each different disease has now it's own unique source name

2020-09-01 23:11 UTC, ypriverol requested changes
Dear @ohwey I have difficulties to understand the SDRF you have same sample 1 associated with two different files and not fractionization. Are this technical replicates?

2020-09-01 23:12 UTC, ypriverol commented on annotated-projects/PXD005507/sdrf.tsv
> +sample1	homo sapiens	"NT=Liver;AC=NCIT:C12392"	epithelial cell	"NT=hepatocellular carcinoma;AC=DOID:684"	"NT=HepG2;AC=EFO:0001187"	OEII15635	OEII15635.raw	ftp://ftp.pride.ebi.ac.uk/pride/data/archive
Dear @ohwey I have difficulties to understand the SDRF you have same sample 1 associated with two different files and not fractionization. Are these technical replicates?

2020-09-07 07:44 UTC, Ohwey commented
Dear @ypriverol in this experiment are 3 treatment groups used. Each treatment group uses 6 experimental/biological replicates. There are no technical or fractional replicates in this experiment.

2020-09-08 22:48 UTC, merged