Add PXD004603,PXD005172,PXD005174,PXD005176
bigbio/proteomics-metadata-standard pull request #507
Opened 2021-01-29 07:37 UTC by 2018g005

2021-01-29 07:45 UTC, ypriverol commented
Dear @2018g005 here the error: 

```
{row: 100, column: "characteristics[organism]"}: "nan" the term name or title can't be found in the ontology -- ncbitaxon
PXD005172	Failed basic validation (sdrf.tsv)
```
The organism can't be nan

2021-01-31 09:15 UTC, daichengxin commented
Dear @2018g005 , here the error in PXD005172: column: `characteristics[individual]`: "not available " contains trailing whitespace. please delete the trailing whitespace. In PXD005174: `facter value[phenotype]` -> `factor value[phenotype]`

2021-02-01 14:23 UTC, ypriverol requested changes
@2018g005 can you do the changes requested by @daichengxin

2021-02-02 07:53 UTC, ypriverol approved these changes

2021-02-02 07:54 UTC, daichengxin approved these changes

2021-02-02 07:56 UTC, merged